apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path:
    path: /data/datadir-mysql-0
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /data/datadir-mysql-1
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /data/datadir-mysql-2
    server: 10.10.10.10
