apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-0
  namespace: middleware
  labels:
    app: mysql
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/galera-0/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-1
  namespace: middleware
  labels:
    app: mysql
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/galera-1/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-2
  namespace: middleware
  labels:
    app: mysql
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/galera-2/datadir
